os: osx
osx_image: xcode9.1
compiler: clang
language: node_js

matrix:
  include:
    - node_js: '10.16'
      env: ELECTRON_VERSION="3.0.0"
    - node_js: '11.15'
      env: ELECTRON_VERSION="4.2.0"
    - node_js: '12'
      env: ELECTRON_VERSION="5.0.0"
    - node_js: '12'
      env: ELECTRON_VERSION="6.0.2"
    - node_js: '12.8.1'
      env: ELECTRON_VERSION="7.1.9"
    - node_js: '12.13.0'
      env: ELECTRON_VERSION="8.2.0"
    - node_js: '12.18.3'
      env: ELECTRON_VERSION="11.0.2"

install:
  - export PACKAGE_VERSION=`node -p "require('./package.json').version"`

  # install electron for tests
  - npm install --global electron@$ELECTRON_VERSION

  # query electron's abi
  - export ELECTRON_ABI=`npx electron --abi`

  # build for nodejs
  - npm install --build-from-source

  # build for electron
  - npm install --build-from-source --runtime=electron --target=$ELECTRON_VERSION --disturl=https://atom.io/download/atom-shell --abi=$ELECTRON_ABI

script:
  # - npm run test
  - echo "Tests are disabled due to issues with automating clicks on macOS"
